name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: joao2206
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Set up Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
      - name: Deploy to GitHub Pages
        run: |
          git add dist
          git commit -m "Deploy to GitHub pages"
          git push origin HEAD:output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
